version: '2'
services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/config:/config'
      - './prometheus/data/prometheus:/prometheus/data'
    command:
      - '--config.file=/config/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=90d'

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.26.0
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox-config:/config

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - './grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana/data:/var/lib/grafana'
